### ISSUE TITLE
Studios Intro Page

### ISSUE THREAD

**Issue by victoria-torres** [engagementlab/engagement-lab-website-2.x#144] opened 2020-10-12 19:28 UTC
There are two Graduate Thesis Studios at the bottom of the page, the furthest one on the right should say co-curricular. It shows up correctly in the CMS but isn't translating in QA

**Comment by johnnycrich** [comment] 2020-10-14 17:47
Duplicate of #141

**Closed by johnnycrich** 2020-10-14 17:47 UTC
Labels: bug
